// Code generated by counterfeiter. DO NOT EDIT.
package formatfakes

import (
	"encoding/json"
	"sync"

	"github.com/gemfire/tanzu-gemfire-management-cf-plugin/impl/common/format"
)

type FakeJSONFilter struct {
	Stub        func(string, string) ([]json.RawMessage, error)
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 string
		arg2 string
	}
	returns struct {
		result1 []json.RawMessage
		result2 error
	}
	returnsOnCall map[int]struct {
		result1 []json.RawMessage
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeJSONFilter) Spy(arg1 string, arg2 string) ([]json.RawMessage, error) {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("JSONFilter", []interface{}{arg1, arg2})
	fake.mutex.Unlock()
	if fake.Stub != nil {
		return fake.Stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.returns.result1, fake.returns.result2
}

func (fake *FakeJSONFilter) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeJSONFilter) Calls(stub func(string, string) ([]json.RawMessage, error)) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *FakeJSONFilter) ArgsForCall(i int) (string, string) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1, fake.argsForCall[i].arg2
}

func (fake *FakeJSONFilter) Returns(result1 []json.RawMessage, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 []json.RawMessage
		result2 error
	}{result1, result2}
}

func (fake *FakeJSONFilter) ReturnsOnCall(i int, result1 []json.RawMessage, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 []json.RawMessage
			result2 error
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 []json.RawMessage
		result2 error
	}{result1, result2}
}

func (fake *FakeJSONFilter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeJSONFilter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ format.JSONFilter = new(FakeJSONFilter).Spy
