// Code generated by counterfeiter. DO NOT EDIT.
package commonfakes

import (
	"net/http"
	"sync"

	"github.com/gemfire/tanzu-gemfire-management-cf-plugin/domain"
	"github.com/gemfire/tanzu-gemfire-management-cf-plugin/impl/common"
)

type FakeRequestBuilder struct {
	Stub        func(domain.RestEndPoint, *domain.CommandData) (*http.Request, error)
	mutex       sync.RWMutex
	argsForCall []struct {
		arg1 domain.RestEndPoint
		arg2 *domain.CommandData
	}
	returns struct {
		result1 *http.Request
		result2 error
	}
	returnsOnCall map[int]struct {
		result1 *http.Request
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRequestBuilder) Spy(arg1 domain.RestEndPoint, arg2 *domain.CommandData) (*http.Request, error) {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		arg1 domain.RestEndPoint
		arg2 *domain.CommandData
	}{arg1, arg2})
	fake.recordInvocation("RequestBuilder", []interface{}{arg1, arg2})
	fake.mutex.Unlock()
	if fake.Stub != nil {
		return fake.Stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.returns.result1, fake.returns.result2
}

func (fake *FakeRequestBuilder) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeRequestBuilder) Calls(stub func(domain.RestEndPoint, *domain.CommandData) (*http.Request, error)) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = stub
}

func (fake *FakeRequestBuilder) ArgsForCall(i int) (domain.RestEndPoint, *domain.CommandData) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].arg1, fake.argsForCall[i].arg2
}

func (fake *FakeRequestBuilder) Returns(result1 *http.Request, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	fake.returns = struct {
		result1 *http.Request
		result2 error
	}{result1, result2}
}

func (fake *FakeRequestBuilder) ReturnsOnCall(i int, result1 *http.Request, result2 error) {
	fake.mutex.Lock()
	defer fake.mutex.Unlock()
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 *http.Request
			result2 error
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 *http.Request
		result2 error
	}{result1, result2}
}

func (fake *FakeRequestBuilder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRequestBuilder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ common.RequestBuilder = new(FakeRequestBuilder).Spy
