---

resources:
  - name: cloudcache-management-cf-plugin
    type: git
    source:
      uri: git@github.com:gemfire/cloudcache-management-cf-plugin.git
      branch: develop
      private_key: ((gemfire-ci-private-key))

jobs:
  - name: build-cloudcache-management-cf-plugin
    serial: true
    plan:
      - aggregate:
          - get: cloudcache-management-cf-plugin
            trigger: true
      - task: build-image
        timeout: 1h
        config:
          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: latest
          inputs:
            - name: cloudcache-management-cf-plugin
          outputs:
            - name: results
          platform: linux
          run:
            path: /bin/sh
            args:
            - -ec
            - |
              cd cloudcache-management-cf-plugin
              go build -o ./pcc ./cmd/main
